import Head from "next/head";
import Image from "next/image.js";
import LOGO from '../public/LOGO.png'
import styles from "@/styles/Home.module.css";
import SideBar from "../components/sideBar.jsx";
import Footer from "@/components/Footer.jsx";
import { BiGridAlt } from "react-icons/bi";
import { FaReact } from "react-icons/fa";
import { CiSearch,CiHeart } from "react-icons/ci";
import { HiOutlineShoppingBag } from "react-icons/hi2";
import { RxPerson } from "react-icons/rx";
import { PiLessThanLight } from "react-icons/pi";
import { useState } from "react";
import { useRef } from "react";
import ProductCard from "@/components/ProductCard";



export default function Home({products}) {
  console.log(products)


  const [isVisible,setIsvisible]=useState(true)


 const productDivGridRef = useRef();
  const handletoggle=()=>{
    setIsvisible(!isVisible);
    // if(isVisible){
    //   let mainElement=document.getElementById('productDivGrid');
    //   mainElement.style.gridTemplateColumns='repeat(4,1fr)'
    // }else{
    //   let mainElement=document.getElementById('productDivGrid');
    //   mainElement.style.gridTemplateColumns='repeat(3,1fr)'

    // }
    if (productDivGridRef.current) {
      productDivGridRef.current.style.gridTemplateColumns = isVisible
        ? "repeat(4, 1fr)"
        : "repeat(3, 1fr)";
    }

  }
  return (
    <>
      <Head>
        <title>Appscript task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        
      >

<div className={styles.uppermostbar}>
              <p className={styles.frame}><BiGridAlt/> Lorem ipsum dolor</p>
              <p className={styles.frame}><BiGridAlt/> Lorem ipsum dolor</p>
              <p className={styles.frame}><BiGridAlt/> Lorem ipsum dolor</p>
            </div>
        <main className={styles.main}>
            
            
            <header className={styles.header}>
                <div className={styles.header1}>
                   <Image src={LOGO} alt="LOGO" style={{width:'36px',height:'36px'}}></Image>
                   <h1>LOGO</h1>
                   <div className={styles.span}>
                     <CiSearch size={24}/>
                     <CiHeart size={24}/>
                     <HiOutlineShoppingBag size={24}/>
                     <RxPerson size={24}/>
                     <select name="ENG" id=""><option value="English" selected>ENG</option></select>
                   </div>
                </div>
                <div className={styles.header2}>
                  
                    <a href="">SHOP</a>
                    <a href="">SKILLS</a>
                    <a href="">STORIES</a>
                    <a href="">ABOUT</a>
                    <a href="">CONTACT US</a>
                </div>
                <hr/>

            </header>
            <div className={styles.middle}>
              <p className={styles.middleheading}>DISCOVER OUR PRODUCTS</p>
              <p className={styles.middlesub}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore rem optio est necessitatibus quis modi facere corporis aut rerum tempore.</p>
            </div>
            <br /><br />
            <hr />

            <div className={styles.bar}>
               <div className={styles.bar1}>
               <p>3425 ITEMS</p>
               <button onClick={handletoggle} className={styles.togglebtn}><PiLessThanLight/> {isVisible?'HIDE FILTER':'SHOW FILTER'}</button>
               </div>
               <select name="recommend" id="" className={styles.select}>
                <option value="recommended" selected>RECOMMENDED</option>
                <option value="newest first">NEWEST FIRST</option>
                <option value="popular">POPULAR</option>
                <option value="high to low">PRICE:HIGH TO LOW</option>
                <option value="low to high">PRICE:LOW TO HIGH</option>
                </select>
               

            </div>
            <hr />
            <br />
           <div style={{display:'flex'}}>
               <div> {isVisible && <SideBar/>}</div>
               <div ref={productDivGridRef} id="productDivGrid" className={styles.productgrid}>
                    {products.map((product) => (
                          <ProductCard key={product.id} product={product} />
                             ))}
    </div>
           </div>
             
           
          
        </main>
        <Footer/>
      </div>
    </>
  );
}





export async function getServerSideProps() {
  const responce = await fetch('https://fakestoreapi.com/products');
  const products = await responce.json();

  return {
    props: {
      products,
      revalidate:3600,
    },
  };
}
